# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/

before_install:
 - sudo apt-get install g++
 - sudo apt-get install clang
 - sudo apt-get install libgtest-dev
 - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"

install:
- echo ${PATH}
- echo ${CXX}
- ${CXX} --version
- ${CXX} -v
addons:
  apt:
    # List of whitelisted in travis packages for ubuntu-precise can be found here:
    #   https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
    # List of whitelisted in travis apt-sources:
    #   https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
   packages:
    - valgrind
    - cmake
    - cmake-data
    
os:
  - linux
  - osx
language: cpp
compiler:
  - gcc
  - clang
script: ./travis.sh
env:
  matrix:
    - TARGET=platform VERBOSE_MAKE=true VERBOSE

notifications:
  email: false
sudo: required
